#Hardware
backend = "glx"
vsync = true

#Shadows
shadow = true 
#shadow-radius = 20
#shadow-offset-x = -6
#shadow-offset-y = -6
#shadow-opacity = 0.6

#Blur
blur-method = "dual_kawase"
blur-strength = 5
blur-background-fixed = false;
blur-background-exclude = [
	"class_g = 'zoom'",
	"class_g = 'nitrogen'",
    "window_type = 'utility'"
];
opacity-rule = [
	"80:class_g = 'polybar'",
];


# Random corners
corner-radius = 9.0;
round-borders = 0;
round-borders-rule = [
  "3:window_type = 'unknown'",
  "3:window_type = 'toolbar'",
  "3:window_type = 'utility'",
  "3:window_type = 'splash'",
  "3:window_type = 'dialog'",
  "3:window_type = 'normal'"
];

rounded-corners-exclude = [
  "class_g = 'dunst'",
  "class_g = 'Polybar'",
];



#################################
#
# Window type settings
#
#################################

wintypes:
{
    tooltip =
    {
        # fade: Fade the particular type of windows.
        fade = false;
        # shadow: Give those windows shadow
        shadow = false;
        # opacity: Default opacity for the type of windows.
        opacity = 0.85;
        # focus: Whether to always consider windows of this type focused.
        focus = true;
    };
};



# Use WM_TRANSIENT_FOR to group windows, and consider windows in the same group focused at the same time.
detect-transient = true;
# Use WM_CLIENT_LEADER to group windows, and consider windows in the same group focused at the same time.
# WM_TRANSIENT_FOR has higher priority if --detect-transient is enabled, too.
detect-client-leader = true;


#################################
#
# Fading
#
#################################

# Fade windows during opacity changes.
fading = false;
# The time between steps in a fade in milliseconds. (default 10).
fade-delta = 4;
# Opacity change between steps while fading in. (default 0.028).
fade-in-step = 0.03;
# Opacity change between steps while fading out. (default 0.03).
fade-out-step = 0.03;
# fade-exclude = ["class_g != 'nitrogen'"]
# Fade windows in/out when opening/closing
# no-fading-openclose = true;
